/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Brewed.java
 *
 * Created on Oct 14, 2012, 1:48:31 PM
 */

package my.Step1;
// Imports JOption Pane\\
import javax.swing.JOptionPane;

/**
 *
 * @author conor
 */
public class Brewed extends javax.swing.JFrame {
     //Creates flag for opening and closing frame\\
     public static boolean brewedFlag=false;

     //Creates flag for prices of each item picked\\
     public static boolean priceBlendFlag=false ;
     public static boolean priceBlendDecafFlag=false ;
     public static boolean priceCafeFlag=false ;
     public static boolean priceFlavFlag=false ;
     public static boolean priceMochaFlag=false ;
     public static boolean priceCapFlag=false ;

     //Creates flag of currnt stock\\
     public static int HouseBlendReg = 4 ;
     public static int HouseBlendDecaf = 4 ;
     public static int CafeAmericano = 4 ;
     public static int FlavouredCoffee = 4 ;
     public static int CafeMocha = 4 ;
     public static int Capuccino = 4 ;







    /** Creates new form Brewed */
    public Brewed() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jButtonReg = new javax.swing.JButton();
        jButtonDecaf = new javax.swing.JButton();
        FlavC = new javax.swing.JButton();
        jButtonAmer = new javax.swing.JButton();
        jButtonCap = new javax.swing.JButton();
        jButtonMocha = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButtonBack = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        jLabel4.setText("€3.00");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 255));
        setMinimumSize(new java.awt.Dimension(587, 455));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jButtonReg.setFont(new java.awt.Font("Trajan Pro", 0, 14));
        jButtonReg.setText("HOUSE BLEND REGULAR");
        jButtonReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonReg);
        jButtonReg.setBounds(280, 80, 240, 23);

        jButtonDecaf.setFont(new java.awt.Font("Trajan Pro", 0, 14));
        jButtonDecaf.setText("HOUSE BLEND DECAF");
        jButtonDecaf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDecafActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDecaf);
        jButtonDecaf.setBounds(280, 110, 240, 23);

        FlavC.setFont(new java.awt.Font("Trajan Pro", 0, 14));
        FlavC.setText("FLAVOURED COFFEE");
        FlavC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlavCActionPerformed(evt);
            }
        });
        getContentPane().add(FlavC);
        FlavC.setBounds(280, 170, 240, 23);

        jButtonAmer.setFont(new java.awt.Font("Trajan Pro", 0, 14));
        jButtonAmer.setText("CAFE AMERICANO");
        jButtonAmer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAmerActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAmer);
        jButtonAmer.setBounds(280, 140, 240, 23);

        jButtonCap.setFont(new java.awt.Font("Trajan Pro", 0, 14));
        jButtonCap.setText("CAPPUCCINO");
        jButtonCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCapActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCap);
        jButtonCap.setBounds(280, 230, 240, 23);

        jButtonMocha.setFont(new java.awt.Font("Trajan Pro", 0, 14));
        jButtonMocha.setText("CAFE MOCHA");
        jButtonMocha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMochaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMocha);
        jButtonMocha.setBounds(280, 200, 240, 23);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14));
        jLabel1.setText("Brewed Coffee & Expresso");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(300, 50, 200, 17);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("€2.50");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(520, 80, 40, 20);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("€2.50");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(520, 110, 40, 20);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("€3.00");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(520, 140, 40, 20);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("€4.50");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(520, 200, 40, 20);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jLabel7.setText("€4.50");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(520, 170, 40, 20);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setText("€5.00");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(520, 230, 40, 20);

        jButtonBack.setFont(new java.awt.Font("Trajan Pro", 0, 18));
        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBack);
        jButtonBack.setBounds(450, 380, 90, 27);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Step2.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 570, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // Takes you back to start frame//
        Step1 Step=new Step1 ();
        Step.setVisible (true) ;
        setVisible (false) ;
        dispose ();
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegActionPerformed
        //Checks if there is enough stock if not sets to red and shows JOptionPane//
        if(HouseBlendReg<=0){
                jButtonReg.setForeground(new java.awt.Color(255, 0, 0));
                JOptionPane.showMessageDialog(null, "Out Of Stock");
        }
    // If there is enough Stock this take you to the next page\\
            else{
                Size Siz=new Size ();
                Siz.setVisible (true) ;
                setVisible (false) ;
                dispose ();
            }

        //Declare which button has been pressed using flags\\
        priceBlendFlag=true;
        priceBlendDecafFlag=false ;
        priceCafeFlag=false ;
        priceFlavFlag=false ;
        priceMochaFlag=false ;
        priceCapFlag=false ;
    }//GEN-LAST:event_jButtonRegActionPerformed

    private void jButtonDecafActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDecafActionPerformed
        //Checks if there is enough stock if not sets to red and shows JOptionPane//
        if(HouseBlendDecaf<=0){
                jButtonDecaf.setForeground(new java.awt.Color(255, 0, 0));
                JOptionPane.showMessageDialog(null, "Out Of Stock");
        }
    // If there is enough Stock this take you to the next page\\
            else{
                Size Siz=new Size ();
                Siz.setVisible (true) ;
                setVisible (false) ;
                dispose ();
            }
        //Declare which button has been pressed using flags\\
        priceBlendDecafFlag=true;
        priceBlendFlag=false;
        priceCafeFlag=false ;
        priceFlavFlag=false ;
        priceMochaFlag=false ;
        priceCapFlag=false ;

    }//GEN-LAST:event_jButtonDecafActionPerformed

    private void FlavCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlavCActionPerformed
        //Checks if there is enough stock if not sets to red and shows JOptionPane//
        if(FlavouredCoffee<=0){
                FlavC.setForeground(new java.awt.Color(255, 0, 0));
                JOptionPane.showMessageDialog(null, "Out Of Stock");
        }
        // If there is enough Stock this take you to the next page\\ 
            else{
                Size Siz=new Size ();
                Siz.setVisible (true) ;
                setVisible (false) ;
                dispose ();
            }

        //Declare which button has been pressed using flags\\
        priceFlavFlag=true;
        priceBlendFlag=false;
        priceBlendDecafFlag=false ;
        priceCafeFlag=false ;
        priceMochaFlag=false ;
        priceCapFlag=false ;
    }//GEN-LAST:event_FlavCActionPerformed

    private void jButtonAmerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAmerActionPerformed
        //Checks if there is enough stock if not sets to red and shows JOptionPane//
        if(CafeAmericano<=0){
                jButtonAmer.setForeground(new java.awt.Color(255, 0, 0));
                JOptionPane.showMessageDialog(null, "Out Of Stock");
        }
         // If there is enough Stock this takes you to the next page\\
            else{
                Size Siz=new Size ();
                Siz.setVisible (true) ;
                setVisible (false) ;
                dispose ();
            }
        //Declare which button has been pressed using flags\\
        priceCafeFlag=true;
        priceBlendFlag=false;
        priceBlendDecafFlag=false ;
        priceFlavFlag=false ;
        priceMochaFlag=false ;
        priceCapFlag=false ;
    }//GEN-LAST:event_jButtonAmerActionPerformed

    private void jButtonCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCapActionPerformed
        //Checks if there is enough stock if not sets to red and shows JOptionPane//
        if(Capuccino<=0){
                jButtonCap.setForeground(new java.awt.Color(255, 0, 0));
                JOptionPane.showMessageDialog(null, "Out Of Stock");
        }
     // If there is enough Stock this takes you to the next page\\
            else{
                Size Siz=new Size ();
                Siz.setVisible (true) ;
                setVisible (false) ;
                dispose ();
            }

        //Declare which button has been pressed using flags\\
        priceCapFlag=true;
        priceBlendFlag=false;
        priceBlendDecafFlag=false ;
        priceCafeFlag=false ;
        priceFlavFlag=false ;
        priceMochaFlag=false ;

    }//GEN-LAST:event_jButtonCapActionPerformed

    private void jButtonMochaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMochaActionPerformed
         //Checks if there is enough stock if not sets to red and shows JOptionPane//
        if(CafeMocha<=0){
                jButtonMocha.setForeground(new java.awt.Color(255, 0, 0));
                JOptionPane.showMessageDialog(null, "Out Of Stock");
        }
    // If there is enough Stock this takes you to the next page\\
            else{
                Size Siz=new Size ();
                Siz.setVisible (true) ;
                setVisible (false) ;
                dispose ();
            }
        //Declare which button has been pressed using flags\\
        priceMochaFlag=true;
        priceBlendFlag=false;
        priceBlendDecafFlag=false ;
        priceCafeFlag=false ;
        priceFlavFlag=false ;
        priceCapFlag=false ;       
    }//GEN-LAST:event_jButtonMochaActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        //Declare which page has been opened using flags\\
        brewedFlag=true;
        my.Step1.Teas.teaFlag=false;
        my.Step1.Speciality.specialFlag=false;
    }//GEN-LAST:event_formWindowActivated

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Brewed().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FlavC;
    private javax.swing.JButton jButtonAmer;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonCap;
    private javax.swing.JButton jButtonDecaf;
    private javax.swing.JButton jButtonMocha;
    private javax.swing.JButton jButtonReg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

}
