/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Pay.java
 *
 * Created on Oct 30, 2012, 12:39:21 AM
 */

package my.Step1;

//imports Decimal format for the money\\
import java.text.DecimalFormat;
//imports JOption Pane\\
import javax.swing.JOptionPane ;

/**
 *
 * @author conor
 */
public class Pay extends javax.swing.JFrame {
    //keeps count of money in the machine\\
    public static int TenCent = 3 ;
    public static int TwentyCent = 3;
    public static int FiftyCent = 3;
    public static int OneEuro = 3;
    public static int TwoEuro = 3;
    
    //keeps count of what coins have been entered into the machine//
    public static int CurrentTenCent = 0 ;
    public static int CurrentTwentyCent = 0 ;
    public static int CurrentFiftyCent = 0 ;
    public static int CurrentOneEuro = 0 ;
    public static int CurrentTwoEuro = 0 ;

    //keeps track of the amount entered//
    public static double Amount=0.0;

private void openEndFrame (){
    //if amount is greather or equal to the price then it goes to end frame otherwise it shows incorect money inserted\\

    double price = Double.parseDouble(jTextDue.getText());
    if(Amount>=price){
        Amount-=price ;
         EndFrame End=new EndFrame ();
         End.setVisible (true) ;
         setVisible (false) ;
         dispose ();
         change(Amount);
    }
    else{
        JOptionPane.showMessageDialog(null ,"Incorect Money Inserted");
        }
}

public void change(double amount){
    //creates a method that calculates what money is given back in the change\\

    while (amount>0.05){
    if ((amount>=2.00)&&(TwoEuro>0)){
        amount-=2.0;
        TwoEuro--;
    }
    else if ((amount>=1.00)&&(OneEuro>0)){
        amount-=1.0;
        OneEuro--;
    }
     else if ((amount>=0.50)&&(FiftyCent>0)){
        amount-=0.50;
        FiftyCent--;
    }

      else if ((amount>=0.20)&&(TwentyCent>0)){
        amount-=0.20;
        TwentyCent--;
    }
     else if ((amount>=0.10)&&(TenCent>0)){
        amount-=0.10;
        TenCent--;
    }
     else{ amount=0.0 ;
     }
    }
}
    /** Creates new form Pay */
    public Pay() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonComfirm = new javax.swing.JButton();
        jButtonReturn = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jTextDue = new javax.swing.JTextField();
        jTextInserted = new javax.swing.JTextField();
        jLabelChoice = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton10Cent = new javax.swing.JButton();
        jButton20Cent = new javax.swing.JButton();
        jButton50Cent = new javax.swing.JButton();
        jButton1Euro = new javax.swing.JButton();
        jButton2Euro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(587, 455));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jButtonComfirm.setText("Comfirm Purchase");
        jButtonComfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComfirmActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonComfirm);
        jButtonComfirm.setBounds(380, 300, 150, 23);

        jButtonReturn.setText("Return Money");
        jButtonReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReturnActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonReturn);
        jButtonReturn.setBounds(380, 340, 150, 23);

        jButtonCancel.setText("Cancel Order");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancel);
        jButtonCancel.setBounds(380, 380, 150, 23);

        jTextDue.setEditable(false);
        jTextDue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDueActionPerformed(evt);
            }
        });
        getContentPane().add(jTextDue);
        jTextDue.setBounds(450, 90, 110, 30);

        jTextInserted.setEditable(false);
        jTextInserted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextInsertedActionPerformed(evt);
            }
        });
        getContentPane().add(jTextInserted);
        jTextInserted.setBounds(440, 250, 110, 30);
        getContentPane().add(jLabelChoice);
        jLabelChoice.setBounds(240, 70, 200, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/PayScreen.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 570, 420);

        jButton10Cent.setOpaque(false);
        jButton10Cent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10CentActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10Cent);
        jButton10Cent.setBounds(280, 160, 60, 30);

        jButton20Cent.setText("jButton1");
        jButton20Cent.setOpaque(false);
        jButton20Cent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20CentActionPerformed(evt);
            }
        });
        getContentPane().add(jButton20Cent);
        jButton20Cent.setBounds(350, 163, 70, 20);

        jButton50Cent.setText("jButton1");
        jButton50Cent.setOpaque(false);
        jButton50Cent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton50CentActionPerformed(evt);
            }
        });
        getContentPane().add(jButton50Cent);
        jButton50Cent.setBounds(430, 160, 73, 30);

        jButton1Euro.setText("jButton1");
        jButton1Euro.setOpaque(false);
        jButton1Euro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1EuroActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1Euro);
        jButton1Euro.setBounds(310, 210, 73, 30);

        jButton2Euro.setText("jButton1");
        jButton2Euro.setOpaque(false);
        jButton2Euro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2EuroActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2Euro);
        jButton2Euro.setBounds(400, 210, 73, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton10CentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10CentActionPerformed
        //adds 10 cent to amount and inserts .10 into jTextInserted\\

        DecimalFormat df = new DecimalFormat("0.00");
        TenCent ++ ;
        Amount = Amount + .10 ;
        jTextInserted.setText(new DecimalFormat("€#0.00").format(+ Amount));
        CurrentTenCent ++ ;

    }//GEN-LAST:event_jButton10CentActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        //checks to see what drink and size has been selected and sets the price to the jTextDue\\

        if (my.Step1.Brewed.priceBlendFlag==true){
           if(my.Step1.Size.Tall==true){
               jTextDue.setText( " 2.50");
           }
           else if (my.Step1.Size.Venti==true){
               jTextDue.setText(" 3.00");
           }
           else {
               jTextDue.setText(" 3.50");
           }
        }
              
        else if (my.Step1.Brewed.priceBlendDecafFlag==true){
            if(my.Step1.Size.Tall==true){
                jTextDue.setText( " 2.50");
            }
           else if (my.Step1.Size.Venti==true){
               jTextDue.setText(" 3.00"); 
           }
           else {
                jTextDue.setText(" 3.50");
           }    
        }
       
        else if (my.Step1.Brewed.priceCafeFlag==true){
            if(my.Step1.Size.Tall==true){
                jTextDue.setText( " 3.00");
            }
            else if (my.Step1.Size.Venti==true){
                jTextDue.setText(" 3.50");
            }
            else {
                jTextDue.setText(" 4.00");
            }
        }
       
        else if (my.Step1.Brewed.priceCapFlag==true){
            if(my.Step1.Size.Tall==true){
                jTextDue.setText( " 5.00");
            }
            else if (my.Step1.Size.Venti==true){
                jTextDue.setText(" 5.50");
            }
            else {
                jTextDue.setText(" 6.00");
            }
        }
        
        else if (my.Step1.Brewed.priceFlavFlag==true){
            if(my.Step1.Size.Tall==true){
                jTextDue.setText( " 4.50");
            }
            else if (my.Step1.Size.Venti==true){
                jTextDue.setText(" 5.00");
            }
            else {
                jTextDue.setText(" 5.50");
            }
        }
        
        else if (my.Step1.Brewed.priceMochaFlag==true){
            if(my.Step1.Size.Tall==true){
                jTextDue.setText( " 4.50");
            }
            else if (my.Step1.Size.Venti==true){
                jTextDue.setText(" 5.00");
            }
            else {
                jTextDue.setText(" 5.50");
            }
        }
        
        //checks to see what drink and size has been selected and sets the price to the jTextDue\\
        
         if (my.Step1.Speciality.priceChocFlag==true){
            if(my.Step1.Size.Tall==true){
                jTextDue.setText( " 3.00");
            }
            else if (my.Step1.Size.Venti==true){
                jTextDue.setText(" 3.50");
            }
            else {
               jTextDue.setText(" 4.00");
            }
        }
        
        else if (my.Step1.Speciality.priceMintChocFlag==true){
            if(my.Step1.Size.Tall==true){
                jTextDue.setText( " 3.50");
            }
            else if (my.Step1.Size.Venti==true){
                jTextDue.setText(" 4.00");
            
            }
            else {
                jTextDue.setText(" 4.50");
            }
        }

        else if (my.Step1.Speciality.priceChickenFlag==true){
            if(my.Step1.Size.Tall==true){
                jTextDue.setText( " 4.00");
            }
            else if (my.Step1.Size.Venti==true){
                jTextDue.setText(" 4.50");
            }
            else {
                jTextDue.setText(" 5.00");
            }
        }
        
        else if (my.Step1.Speciality.priceVegetableFlag==true){
            if(my.Step1.Size.Tall==true){
                jTextDue.setText( " 4.00");
            }
            else if (my.Step1.Size.Venti==true){
                jTextDue.setText(" 4.50");
            }
            else {
                jTextDue.setText(" €5.00");
            }
        }

         //checks to see what drink and size has been selected and sets the price to the jTextDue\\

        if (my.Step1.Teas.priceGoldBlend==true){
           if(my.Step1.Size.Tall==true){
           jTextDue.setText( " 2.00");
            }
           else if (my.Step1.Size.Venti==true){
           jTextDue.setText(" 2.50");

            }
           else {
               jTextDue.setText(" 3.00");

            }
            }
       if (my.Step1.Teas.priceGreenTea==true){
           if(my.Step1.Size.Tall==true){
           jTextDue.setText( " 2.00");
            }
           else if (my.Step1.Size.Venti==true){
           jTextDue.setText(" 2.50");

            }
           else {
               jTextDue.setText(" 3.00");

            }
            }
       if (my.Step1.Teas.pricePepGreenTea==true){
           if(my.Step1.Size.Tall==true){
           jTextDue.setText( " 3.00");
            }
           else if (my.Step1.Size.Venti==true){
           jTextDue.setText(" 3.50");

            }
           else {
               jTextDue.setText(" 4.00");

            }
            }
       //Sets jLabelChoice to the name of the drink from the Speciality Category//

        if(my.Step1.Speciality.priceChickenFlag==true){
           jLabelChoice.setText("Chicken Soup");
       }
        if(my.Step1.Speciality.priceChocFlag==true){
           jLabelChoice.setText("Hot Chocolate");
        }
        if(my.Step1.Speciality.priceMintChocFlag==true){
           jLabelChoice.setText("Mint Hot Chocolate");
        }
        if(my.Step1.Speciality.priceVegetableFlag==true){
           jLabelChoice.setText("Vegatable Soup");
        }
      
       //Sets jLabelChoice to the name of the drink from the Brewed Category//

       if(my.Step1.Brewed.priceBlendFlag==true){
           jLabelChoice.setText("House Blend Regular");
       }
       if(my.Step1.Brewed.priceBlendDecafFlag==true){
           jLabelChoice.setText("House Blend Decaf");
       }
       if(my.Step1.Brewed.priceCafeFlag==true){
           jLabelChoice.setText("Cafe Americano");
       }
       if(my.Step1.Brewed.priceCapFlag==true){
           jLabelChoice.setText("Cappouchino");
       }
       if(my.Step1.Brewed.priceFlavFlag==true){
           jLabelChoice.setText("Flavoured Coffee");
       }
       if(my.Step1.Brewed.priceMochaFlag==true){
           jLabelChoice.setText("Cafe Mocha");
       }
      
       //Sets jLabelChoice to the name of the drink from the Tea Category//

        if(my.Step1.Teas.priceGoldBlend==true){
           jLabelChoice.setText("Gold Blend");
        }
        if(my.Step1.Teas.priceGreenTea==true){
           jLabelChoice.setText("Green Tea");
        }
        if(my.Step1.Teas.pricePepGreenTea==true){
           jLabelChoice.setText("Peppermint green Tea");
        }
      
           
      
       
}//GEN-LAST:event_formWindowActivated
        
    
    private void jTextDueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDueActionPerformed
        
}//GEN-LAST:event_jTextDueActionPerformed

    private void jButton20CentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20CentActionPerformed
        //adds 20 cent to amount and inserts .20 into jTextInserted\\

        DecimalFormat df = new DecimalFormat("€#0.00");
        TwentyCent ++ ;
        Amount = Amount + .20 ;
        jTextInserted.setText(new DecimalFormat("€#0.00").format(+ Amount));
        CurrentTwentyCent ++ ;
    }//GEN-LAST:event_jButton20CentActionPerformed

    private void jButton50CentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton50CentActionPerformed
        //adds 50 cent to amount and inserts .50 into jTextInserted\\

        DecimalFormat df = new DecimalFormat("€#0.00");
        FiftyCent ++ ;
        Amount = Amount + .50 ;
        jTextInserted.setText(new DecimalFormat("€#0.00").format(+ Amount));
        CurrentFiftyCent ++ ;
    }//GEN-LAST:event_jButton50CentActionPerformed

    private void jButton1EuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1EuroActionPerformed
        //adds One Euro to amount and inserts 1.00 into jTextInserted\\

        DecimalFormat df = new DecimalFormat("€#.00");
        OneEuro ++ ;
        Amount = Amount + 1.00 ;
        jTextInserted.setText(new DecimalFormat("€#.00").format(+ Amount));
        CurrentOneEuro ++ ;
    }//GEN-LAST:event_jButton1EuroActionPerformed

    private void jButton2EuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2EuroActionPerformed
        //adds Two Euro to amount and inserts 2.00 into jTextInserted\\

        DecimalFormat df = new DecimalFormat("€#.00");
        TwoEuro ++ ;
        Amount = Amount + 2.00 ;
        jTextInserted.setText(new DecimalFormat("€#.00").format(+ Amount));
        CurrentTwoEuro ++ ;
    }//GEN-LAST:event_jButton2EuroActionPerformed

    private void jTextInsertedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextInsertedActionPerformed
       

    }//GEN-LAST:event_jTextInsertedActionPerformed

    private void jButtonReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReturnActionPerformed
       //does the calculation and returnes the money inserted//

        String cancelAmount="";

       TenCent=TenCent+CurrentTenCent;
       TwentyCent=TwentyCent+CurrentTwentyCent;
       FiftyCent=FiftyCent+CurrentFiftyCent;
       OneEuro=OneEuro+CurrentOneEuro;
       TwoEuro=TwoEuro+CurrentTwoEuro;

       cancelAmount= ""+CurrentTenCent+": 10cent"+CurrentTwentyCent+": 20cent"+
                     CurrentFiftyCent+": 50cent"+CurrentOneEuro+": 1Euro" +CurrentTwoEuro+": 2Euro";

       CurrentTenCent=0 ;
       CurrentTwentyCent=0 ;
       CurrentFiftyCent=0 ;
       CurrentOneEuro=0 ;
       CurrentTwoEuro=0 ;

       my.Step1.Brewed.priceBlendFlag=false;
       my.Step1.Brewed.priceBlendDecafFlag=false;
       my.Step1.Brewed.priceCafeFlag=false;
       my.Step1.Brewed.priceCapFlag=false;
       my.Step1.Brewed.priceFlavFlag=false;
       my.Step1.Brewed.priceMochaFlag=false;



       jTextInserted.setText("");
        Amount=0.0 ;
    }//GEN-LAST:event_jButtonReturnActionPerformed

    private void jButtonComfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComfirmActionPerformed
       //Checks to see if there is enough stock and runs the End Frame Method \\
        
        if(my.Step1.Brewed.priceBlendFlag==true){
            if(my.Step1.Brewed.HouseBlendReg >0){
                my.Step1.Brewed.HouseBlendReg -- ;
                openEndFrame ();
            }
        }
        else if(my.Step1.Brewed.priceBlendDecafFlag==true){
            if(my.Step1.Brewed.HouseBlendDecaf >0){
                my.Step1.Brewed.HouseBlendDecaf -- ;
                openEndFrame ();
            }
        }
        else if(my.Step1.Brewed.priceCafeFlag==true){
            if(my.Step1.Brewed.CafeAmericano >0){
                my.Step1.Brewed.CafeAmericano -- ;
                openEndFrame ();
            }
        }
        else if(my.Step1.Brewed.priceFlavFlag==true){
            if(my.Step1.Brewed.FlavouredCoffee >0){
                my.Step1.Brewed.FlavouredCoffee -- ;
                openEndFrame ();
            }
        }
        else if(my.Step1.Brewed.priceMochaFlag==true){
            if(my.Step1.Brewed.CafeMocha >0){
                my.Step1.Brewed.CafeMocha -- ;
                openEndFrame ();
            }
        }
        else if(my.Step1.Brewed.priceCapFlag==true){
            if(my.Step1.Brewed.Capuccino >0){
                my.Step1.Brewed.Capuccino-- ;
                openEndFrame ();
            }
        }
        else if(my.Step1.Teas.priceGoldBlend==true){
            if(my.Step1.Teas.GoldBlend >0){
                my.Step1.Teas.GoldBlend -- ;
                openEndFrame ();
            }
        }
        else if(my.Step1.Teas.priceGreenTea==true){
            if(my.Step1.Teas.GreenTea>0){
                my.Step1.Teas.GreenTea -- ;
                openEndFrame ();
            }
        }
        else if(my.Step1.Teas.pricePepGreenTea==true){
            if(my.Step1.Teas.PepGreenTea>0){
                my.Step1.Teas.PepGreenTea -- ;
                openEndFrame ();
            }
        }
        else if(my.Step1.Speciality.priceChickenFlag==true){
            if(my.Step1.Speciality.ChickenSoup>0){
                my.Step1.Speciality.ChickenSoup -- ;
                openEndFrame ();
            }
        }
        else if(my.Step1.Speciality.priceChocFlag==true){
            if(my.Step1.Speciality.HotChoc >0){
                my.Step1.Speciality.HotChoc -- ;
                openEndFrame ();
            }
        }
        else if(my.Step1.Speciality.priceVegetableFlag==true){
            if(my.Step1.Speciality.VegSoup >0){
                my.Step1.Speciality.VegSoup -- ;
                openEndFrame ();
            }
        }
        else if(my.Step1.Speciality.priceMintChocFlag==true){
            if(my.Step1.Speciality.MintChoc >0){
                my.Step1.Speciality.MintChoc -- ;
                openEndFrame ();
            }
        }
      
    }//GEN-LAST:event_jButtonComfirmActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        //Cancels Tansactions and goes back to start frame//

        my.Step1.Brewed.brewedFlag=false;
        my.Step1.Teas.teaFlag=false;
        my.Step1.Speciality.specialFlag=false;

        my.Step1.Brewed.priceBlendFlag=false;
        my.Step1.Brewed.priceBlendDecafFlag=false;
        my.Step1.Brewed.priceCafeFlag=false;
        my.Step1.Brewed.priceFlavFlag=false;
        my.Step1.Brewed.priceMochaFlag=false;
        my.Step1.Brewed.priceCapFlag=false;

        my.Step1.Teas.priceGoldBlend=false;
        my.Step1.Teas.priceGreenTea=false;
        my.Step1.Teas.pricePepGreenTea=false;

        my.Step1.Speciality.priceChickenFlag=false;
        my.Step1.Speciality.priceChocFlag=false;
        my.Step1.Speciality.priceMintChocFlag=false;
        my.Step1.Speciality.priceVegetableFlag=false;

        Amount=0.0 ;
        jTextDue.setText("");
        jTextInserted.setText("");

        Step1 Step=new Step1 ();
        Step.setVisible (true) ;
        setVisible (false) ;
        dispose ();

        
    }//GEN-LAST:event_jButtonCancelActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10Cent;
    private javax.swing.JButton jButton1Euro;
    private javax.swing.JButton jButton20Cent;
    private javax.swing.JButton jButton2Euro;
    private javax.swing.JButton jButton50Cent;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonComfirm;
    private javax.swing.JButton jButtonReturn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelChoice;
    private javax.swing.JTextField jTextDue;
    private javax.swing.JTextField jTextInserted;
    // End of variables declaration//GEN-END:variables

}
