/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Size.java
 *
 * Created on Oct 14, 2012, 2:51:05 PM
 */

package my.Step1;

/**
 *
 * @author conor
 */
public class Size extends javax.swing.JFrame {
    //Declare which size has been picked using flags\\
    public static boolean Tall=false ;
    public static boolean Venti=false;
    public static boolean Trenta=false;


    /** Creates new form Size */
    public Size() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButtonBack = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonTall = new javax.swing.JButton();
        jButtonVenti = new javax.swing.JButton();
        jButtonTrenta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(587, 455));
        getContentPane().setLayout(null);

        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBack);
        jButtonBack.setBounds(445, 380, 80, 23);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("€1 Extra");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(480, 250, 60, 15);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("50c Extra");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(370, 250, 70, 15);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Size.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 560, 420);

        jButtonTall.setText("jButton1");
        jButtonTall.setOpaque(false);
        jButtonTall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTallActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTall);
        jButtonTall.setBounds(280, 140, 73, 110);

        jButtonVenti.setText("jButton1");
        jButtonVenti.setOpaque(false);
        jButtonVenti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVentiActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVenti);
        jButtonVenti.setBounds(363, 110, 80, 140);

        jButtonTrenta.setText("jButton1");
        jButtonTrenta.setOpaque(false);
        jButtonTrenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTrentaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTrenta);
        jButtonTrenta.setBounds(460, 80, 90, 170);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Creates method to open the pay frame\\
    private void openPay (){
         Pay Pa=new Pay ();
         Pa.setVisible (true) ;
         setVisible (false) ;
         dispose ();
         setVisible (false);
         dispose ();

    }
    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        //brings you back to which ever frame you where in\\
        if (my.Step1.Speciality.specialFlag==true){
            Speciality Spec=new Speciality  ();
            Spec.setVisible (true) ;
            setVisible (false) ;
            dispose ();

        }
        else if(my.Step1.Brewed.brewedFlag==true){
            Brewed Bre=new Brewed ();
            Bre.setVisible (true) ;
            setVisible (false) ;
            dispose ();
        }
        else if(my.Step1.Teas.teaFlag==true){
            Teas tea=new Teas ();
            tea.setVisible (true) ;
            setVisible (false) ;
            dispose ();

        }
       
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonTallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTallActionPerformed
        //uses the method to go to the pay frame\\
        openPay();

        //using the flag to find out which size has been picked\\
        Tall=true;
        Venti=false;
        Trenta=false;
    }//GEN-LAST:event_jButtonTallActionPerformed

    private void jButtonVentiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVentiActionPerformed
        //uses the method to go to the pay frame\\
        openPay();
        //using the flag to find out which size has been picked\\
        Tall=false;
        Venti=true;
        Trenta=false;
    }//GEN-LAST:event_jButtonVentiActionPerformed

    private void jButtonTrentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTrentaActionPerformed
        //uses the method to go to the pay frame\\
        openPay();
        //using the flag to find out which size has been picked\\
        Tall=false;
        Venti=false;
        Trenta=true;
    }//GEN-LAST:event_jButtonTrentaActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Size().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonTall;
    private javax.swing.JButton jButtonTrenta;
    private javax.swing.JButton jButtonVenti;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

}
