/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Step1.java
 *
 * Created on Oct 14, 2012, 1:39:48 PM
 */

package my.Step1;
//Imports JOptionPane\\
import javax.swing.JOptionPane ;
//Imports the Password Field for the staff page\\
import javax.swing.JPasswordField;




/**
 *
 * @author conor
 */
public class Step1 extends javax.swing.JFrame {
      
  
    /** Creates new form Step1 */
    public Step1() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonBrew = new javax.swing.JButton();
        jButtonHotT = new javax.swing.JButton();
        jButtonSpecD = new javax.swing.JButton();
        jButtonStaff = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(577, 455));
        getContentPane().setLayout(null);

        jButtonBrew.setFont(new java.awt.Font("Trajan Pro", 1, 18));
        jButtonBrew.setText("Brewed coffee & expresso");
        jButtonBrew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrewActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBrew);
        jButtonBrew.setBounds(234, 100, 320, 30);

        jButtonHotT.setFont(new java.awt.Font("Trajan Pro", 1, 18));
        jButtonHotT.setText("Hot gourmet tea");
        jButtonHotT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHotTActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonHotT);
        jButtonHotT.setBounds(240, 140, 310, 23);

        jButtonSpecD.setFont(new java.awt.Font("Trajan Pro", 1, 18));
        jButtonSpecD.setText("Specialty Drinks");
        jButtonSpecD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSpecDActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSpecD);
        jButtonSpecD.setBounds(240, 180, 310, 23);

        jButtonStaff.setText("Staff Log In ");
        jButtonStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStaffActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonStaff);
        jButtonStaff.setBounds(400, 390, 130, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Step2.png"))); // NOI18N
        jLabel1.setMinimumSize(new java.awt.Dimension(567, 426));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 567, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBrewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrewActionPerformed
        //Takes you to Brewed Frame\\
        Brewed Bre=new Brewed ();
        Bre.setVisible (true) ;
        setVisible (false) ;
        dispose ();
    }//GEN-LAST:event_jButtonBrewActionPerformed

    private void jButtonHotTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHotTActionPerformed
        //Takes you to Teas frame\\
        Teas Tea=new Teas ();
        Tea.setVisible (true) ;
        setVisible (false) ;
        dispose ();
    }//GEN-LAST:event_jButtonHotTActionPerformed

    private void jButtonSpecDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSpecDActionPerformed
        //Takes you to Speciality frame\\
        Speciality Spec=new Speciality ();
        Spec.setVisible (true) ;
        setVisible (false) ;
        dispose ();
    }//GEN-LAST:event_jButtonSpecDActionPerformed

    private void jButtonStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStaffActionPerformed
    //Sets up password on JOption Pane if correct take you to stock page\\
    JPasswordField pwd = new JPasswordField(10);
    int action = JOptionPane.showConfirmDialog(null, pwd,"Enter Password",JOptionPane.OK_CANCEL_OPTION);
    if(action < 0)JOptionPane.showMessageDialog(null,"Cancel, X or escape key selected");
    else {
        String password = new String( pwd.getPassword());
        if (password.equals("pass")){

        Stock Sto=new Stock ();
        Sto.setVisible (true) ;
        setVisible (false) ;
        dispose ();
        }
        else{ JOptionPane.showMessageDialog(null, "Incorrect password");
    }
    }
    }//GEN-LAST:event_jButtonStaffActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
       
                


       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Step1().setVisible(true);
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBrew;
    private javax.swing.JButton jButtonHotT;
    private javax.swing.JButton jButtonSpecD;
    private javax.swing.JButton jButtonStaff;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
