/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Stock.java
 *
 * Created on Nov 2, 2012, 12:39:53 PM
 */

package my.Step1;

/**
 *
 * @author conor
 */
public class Stock extends javax.swing.JFrame {

    /** Creates new form Stock */
    public Stock() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelHouseBlend = new javax.swing.JLabel();
        jTextFieldHouseReg = new javax.swing.JTextField();
        jLabelHouseBlendDecaf = new javax.swing.JLabel();
        jTextFieldHouseDecaf = new javax.swing.JTextField();
        HouseBlendRegUpdate = new javax.swing.JTextField();
        HouseBlendDecafUpdate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldAmericano = new javax.swing.JTextField();
        CafeAmerUpdate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldFlavCoffee = new javax.swing.JTextField();
        FlavCoffeeUpdate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldMocha = new javax.swing.JTextField();
        CafeMochaUpdate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldCapp = new javax.swing.JTextField();
        CappUpdate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        BrewedUpdateStock = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextGoldBlend = new javax.swing.JTextField();
        GoldBlendUpdate = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextGreenTea = new javax.swing.JTextField();
        GreenTeaUpdate = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextPepGreenTea = new javax.swing.JTextField();
        PepGreenTeaUpdate = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        TeasUpdateStock = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextHotChocolate = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextMintChoc = new javax.swing.JTextField();
        MintHotChocUpdate = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextChikSoup = new javax.swing.JTextField();
        ChikSoupUpdate = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        VegSoupUpdate = new javax.swing.JTextField();
        jTextVegSoup = new javax.swing.JTextField();
        SpecialityUpdateStock = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextTwoEuro = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextOneEuro = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jTextFiftyCent = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextTwentyCent = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextFieldTenCent = new javax.swing.JTextField();
        CoinsUpdateStock = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        HotChocUpdate = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        TwoEuroUpdate = new javax.swing.JTextField();
        OneEuroUpdate = new javax.swing.JTextField();
        TwentyCentUpdate = new javax.swing.JTextField();
        TenCentUpdate = new javax.swing.JTextField();
        FiftyCentUpdate = new javax.swing.JTextField();
        jButtonBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabelHouseBlend.setText("House Blend Reg");

        jTextFieldHouseReg.setEditable(false);
        jTextFieldHouseReg.setBorder(new javax.swing.border.SoftBevelBorder(0));
        jTextFieldHouseReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHouseRegActionPerformed(evt);
            }
        });

        jLabelHouseBlendDecaf.setText("House Blend Decaf");

        jTextFieldHouseDecaf.setEditable(false);
        jTextFieldHouseDecaf.setBorder(new javax.swing.border.SoftBevelBorder(0));

        HouseBlendRegUpdate.setText("0");

        HouseBlendDecafUpdate.setText("0");

        jLabel3.setText("Cafe Americano");

        jTextFieldAmericano.setEditable(false);
        jTextFieldAmericano.setBorder(new javax.swing.border.SoftBevelBorder(0));

        CafeAmerUpdate.setText("0");

        jLabel4.setText("Flavoured Coffee");

        jTextFieldFlavCoffee.setEditable(false);
        jTextFieldFlavCoffee.setBorder(new javax.swing.border.SoftBevelBorder(0));

        FlavCoffeeUpdate.setText("0");

        jLabel5.setText("Cafe Mocha");

        jTextFieldMocha.setEditable(false);
        jTextFieldMocha.setBorder(new javax.swing.border.SoftBevelBorder(0));

        CafeMochaUpdate.setText("0");

        jLabel6.setText("Cappuchino");

        jTextFieldCapp.setEditable(false);
        jTextFieldCapp.setBorder(new javax.swing.border.SoftBevelBorder(0));

        CappUpdate.setText("0");

        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jLabel7.setText("Current Stock");

        BrewedUpdateStock.setForeground(new java.awt.Color(204, 0, 0));
        BrewedUpdateStock.setText("UPDATE STOCK");
        BrewedUpdateStock.setBorder(null);
        BrewedUpdateStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrewedUpdateStockActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setText("BREWED");

        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("TEAS");

        jLabel10.setText("Gold Blend");

        jTextGoldBlend.setEditable(false);
        jTextGoldBlend.setBorder(new javax.swing.border.SoftBevelBorder(0));

        GoldBlendUpdate.setText("0");

        jLabel11.setText("Green Tea");

        jTextGreenTea.setEditable(false);
        jTextGreenTea.setBorder(new javax.swing.border.SoftBevelBorder(0));

        GreenTeaUpdate.setText("0");

        jLabel12.setText("Pepermint Green Tea");

        jTextPepGreenTea.setEditable(false);
        jTextPepGreenTea.setBorder(new javax.swing.border.SoftBevelBorder(0));

        PepGreenTeaUpdate.setText("0");

        jLabel13.setForeground(new java.awt.Color(204, 0, 0));
        jLabel13.setText("Curent Stock");

        TeasUpdateStock.setForeground(new java.awt.Color(153, 0, 0));
        TeasUpdateStock.setText("UPDATE STOCK");
        TeasUpdateStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeasUpdateStockActionPerformed(evt);
            }
        });

        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("SPECIALITY");

        jLabel15.setText("Hot Chocolate");

        jTextHotChocolate.setEditable(false);
        jTextHotChocolate.setBorder(new javax.swing.border.SoftBevelBorder(0));

        jLabel16.setText("Mint Hot Chocolate");

        jTextMintChoc.setEditable(false);
        jTextMintChoc.setBorder(new javax.swing.border.SoftBevelBorder(0));

        MintHotChocUpdate.setText("0");

        jLabel17.setText("Chicken Soup");

        jTextChikSoup.setEditable(false);
        jTextChikSoup.setBorder(new javax.swing.border.SoftBevelBorder(0));

        ChikSoupUpdate.setText("0");

        jLabel18.setText("Vegetable Soup");

        VegSoupUpdate.setText("0");

        jTextVegSoup.setEditable(false);
        jTextVegSoup.setBorder(new javax.swing.border.SoftBevelBorder(0));

        SpecialityUpdateStock.setForeground(new java.awt.Color(204, 0, 0));
        SpecialityUpdateStock.setText("UPDATE STOCK");
        SpecialityUpdateStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpecialityUpdateStockActionPerformed(evt);
            }
        });

        jLabel19.setForeground(new java.awt.Color(204, 0, 0));
        jLabel19.setText("COINS");

        jLabel20.setText("Two Euro");

        jTextTwoEuro.setEditable(false);
        jTextTwoEuro.setBorder(new javax.swing.border.SoftBevelBorder(0));

        jLabel21.setText("One Euro");

        jTextOneEuro.setEditable(false);
        jTextOneEuro.setBorder(new javax.swing.border.SoftBevelBorder(0));

        jLabel22.setText("Fifty Cent");

        jTextFiftyCent.setEditable(false);
        jTextFiftyCent.setBorder(new javax.swing.border.SoftBevelBorder(0));

        jLabel23.setText("Twenty Cent");

        jTextTwentyCent.setEditable(false);
        jTextTwentyCent.setBorder(new javax.swing.border.SoftBevelBorder(0));

        jLabel24.setText("Ten Cent");

        jTextFieldTenCent.setEditable(false);
        jTextFieldTenCent.setBorder(new javax.swing.border.SoftBevelBorder(0));

        CoinsUpdateStock.setForeground(new java.awt.Color(204, 0, 0));
        CoinsUpdateStock.setText("UPDATE STOCK");
        CoinsUpdateStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoinsUpdateStockActionPerformed(evt);
            }
        });

        jLabel25.setForeground(new java.awt.Color(204, 0, 0));
        jLabel25.setText("Current Stock");

        HotChocUpdate.setText("0");

        jLabel26.setForeground(new java.awt.Color(204, 0, 0));
        jLabel26.setText("Current Stock");

        jLabel27.setFont(new java.awt.Font("Simplified Arabic", 1, 24));
        jLabel27.setForeground(new java.awt.Color(153, 0, 0));
        jLabel27.setText("Checking and updating stock ");

        TwoEuroUpdate.setText("0");

        OneEuroUpdate.setText("0");

        TwentyCentUpdate.setText("0");

        TenCentUpdate.setText("0");

        FiftyCentUpdate.setText("0");

        jButtonBack.setText("BACK");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BrewedUpdateStock, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel19))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextTwoEuro, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextOneEuro, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jTextFiftyCent, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextTwentyCent, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldTenCent, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(2, 2, 2)))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FiftyCentUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TwentyCentUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TenCentUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(OneEuroUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TwoEuroUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(80, 80, 80)
                                        .addComponent(CoinsUpdateStock, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelHouseBlendDecaf)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabelHouseBlend)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel7)
                                            .addComponent(jTextFieldMocha)
                                            .addComponent(jTextFieldFlavCoffee)
                                            .addComponent(jTextFieldAmericano)
                                            .addComponent(jTextFieldHouseDecaf)
                                            .addComponent(jTextFieldHouseReg, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                            .addComponent(jTextFieldCapp))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CappUpdate)
                                    .addComponent(CafeMochaUpdate)
                                    .addComponent(FlavCoffeeUpdate)
                                    .addComponent(CafeAmerUpdate)
                                    .addComponent(HouseBlendDecafUpdate)
                                    .addComponent(HouseBlendRegUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addContainerGap(287, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addContainerGap(262, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel16)
                                                    .addComponent(jLabel15)
                                                    .addComponent(jLabel17)
                                                    .addComponent(jLabel18))
                                                .addGap(16, 16, 16))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTextPepGreenTea, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jTextGoldBlend, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel13)
                                                        .addComponent(jTextGreenTea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(31, 31, 31)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(PepGreenTeaUpdate)
                                                    .addComponent(GreenTeaUpdate)
                                                    .addComponent(GoldBlendUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jTextHotChocolate, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jTextMintChoc, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jLabel26))
                                                        .addGap(37, 37, 37))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jTextChikSoup, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jTextVegSoup, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(MintHotChocUpdate, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(HotChocUpdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                                                        .addComponent(ChikSoupUpdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(VegSoupUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(SpecialityUpdateStock, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TeasUpdateStock, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(43, 43, 43))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBack)
                        .addGap(69, 69, 69))))
            .addGroup(layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(jLabel27)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextGoldBlend, jTextGreenTea, jTextPepGreenTea});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextChikSoup, jTextHotChocolate, jTextMintChoc, jTextVegSoup});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {OneEuroUpdate, TenCentUpdate, TwentyCentUpdate, TwoEuroUpdate});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelHouseBlend)
                            .addComponent(jTextFieldHouseReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HouseBlendRegUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(GoldBlendUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelHouseBlendDecaf)
                            .addComponent(jTextFieldHouseDecaf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HouseBlendDecafUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(GreenTeaUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextGoldBlend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextGreenTea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldAmericano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CafeAmerUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PepGreenTeaUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jTextPepGreenTea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldFlavCoffee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FlavCoffeeUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldMocha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CafeMochaUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldCapp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CappUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(TeasUpdateStock)
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(BrewedUpdateStock, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextHotChocolate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(HotChocUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(MintHotChocUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextMintChoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ChikSoupUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextVegSoup, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(VegSoupUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel17)
                                            .addComponent(jTextChikSoup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel18)))))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SpecialityUpdateStock)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel21)
                                    .addComponent(jTextOneEuro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextTwoEuro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TwoEuroUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(OneEuroUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel22)
                                    .addComponent(jTextFiftyCent, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel23)
                                    .addComponent(jTextTwentyCent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(FiftyCentUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TwentyCentUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(jTextFieldTenCent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TenCentUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CoinsUpdateStock)
                    .addComponent(jButtonBack))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {OneEuroUpdate, TenCentUpdate, TwentyCentUpdate, TwoEuroUpdate});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldHouseRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHouseRegActionPerformed

    }//GEN-LAST:event_jTextFieldHouseRegActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
          
          //Inserts the stock of the Brewed and Expresso page
          jTextFieldHouseReg.setText(my.Step1.Brewed.HouseBlendReg+"");
          jTextFieldHouseDecaf.setText(my.Step1.Brewed.HouseBlendDecaf+"");
          jTextFieldAmericano.setText(my.Step1.Brewed.CafeAmericano+"");
          jTextFieldMocha.setText(my.Step1.Brewed.CafeMocha+"");
          jTextFieldCapp.setText(my.Step1.Brewed.Capuccino+"");
          jTextFieldFlavCoffee.setText(my.Step1.Brewed.FlavouredCoffee+"");

          //Inserts the stock of the Teas page
          jTextGoldBlend.setText(my.Step1.Teas.GoldBlend+"");
          jTextGreenTea.setText(my.Step1.Teas.GreenTea+"");
          jTextPepGreenTea.setText(my.Step1.Teas.PepGreenTea+"");

          //inserts the stock of the Speciality page
          jTextHotChocolate.setText(my.Step1.Speciality.HotChoc+"");
          jTextMintChoc.setText(my.Step1.Speciality.MintChoc+"");
          jTextChikSoup.setText(my.Step1.Speciality.ChickenSoup+"");
          jTextVegSoup.setText(my.Step1.Speciality.VegSoup+"");

          //inserts the stock of the money currently in the page
          jTextTwoEuro.setText(my.Step1.Pay.TwoEuro+"");
          jTextOneEuro.setText(my.Step1.Pay.OneEuro+"");
          jTextFiftyCent.setText(my.Step1.Pay.FiftyCent+"");
          jTextTwentyCent.setText(my.Step1.Pay.TwentyCent+"");
          jTextFieldTenCent.setText(my.Step1.Pay.TenCent+"");



          
    }//GEN-LAST:event_formWindowActivated

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
       //When Clicked returns to start menu\\
        Step1 Step=new Step1 ();
        Step.setVisible (true) ;
        setVisible (false) ;
        dispose ();
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void BrewedUpdateStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrewedUpdateStockActionPerformed
        //updates stock of brewed\\
        my.Step1.Brewed.HouseBlendReg+=Integer.parseInt(HouseBlendRegUpdate.getText());
        jTextFieldHouseReg.setText(my.Step1.Brewed.HouseBlendReg+"");
        HouseBlendRegUpdate.setText("0");
        
        my.Step1.Brewed.HouseBlendDecaf+=Integer.parseInt(HouseBlendDecafUpdate.getText());
        jTextFieldHouseDecaf.setText(my.Step1.Brewed.HouseBlendDecaf+"");
        HouseBlendDecafUpdate.setText("0");

        my.Step1.Brewed.CafeAmericano+=Integer.parseInt(CafeAmerUpdate.getText());
        jTextFieldAmericano.setText(my.Step1.Brewed.CafeAmericano+"");
        CafeAmerUpdate.setText("0");

        my.Step1.Brewed.CafeMocha+=Integer.parseInt(CafeMochaUpdate.getText());
        jTextFieldMocha.setText(my.Step1.Brewed.CafeMocha+"");
        CafeMochaUpdate.setText("0");

        my.Step1.Brewed.FlavouredCoffee+=Integer.parseInt(FlavCoffeeUpdate.getText());
        jTextFieldFlavCoffee.setText(my.Step1.Brewed.FlavouredCoffee+"");
        FlavCoffeeUpdate.setText("0");
        
        my.Step1.Brewed.Capuccino+=Integer.parseInt(CappUpdate.getText());
        jTextFieldCapp.setText(my.Step1.Brewed.Capuccino+"");
        CappUpdate.setText("0");

            
        
      
    }//GEN-LAST:event_BrewedUpdateStockActionPerformed

    private void TeasUpdateStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeasUpdateStockActionPerformed
        //Updates Teas stock\\
        my.Step1.Teas.GoldBlend+=Integer.parseInt(GoldBlendUpdate.getText());
        jTextGoldBlend.setText(my.Step1.Teas.GoldBlend+"");
        GoldBlendUpdate.setText("0");

        my.Step1.Teas.GreenTea+=Integer.parseInt(GreenTeaUpdate.getText());
        jTextGreenTea.setText(my.Step1.Teas.GreenTea+"");
        GreenTeaUpdate.setText("0");

        my.Step1.Teas.PepGreenTea+=Integer.parseInt(PepGreenTeaUpdate.getText());
        jTextPepGreenTea.setText(my.Step1.Teas.PepGreenTea+"");
        PepGreenTeaUpdate.setText("0");
    }//GEN-LAST:event_TeasUpdateStockActionPerformed

    private void SpecialityUpdateStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpecialityUpdateStockActionPerformed
        //Updates Speciality Stock\\
        my.Step1.Speciality.HotChoc+=Integer.parseInt(HotChocUpdate.getText());
        jTextHotChocolate.setText(my.Step1.Speciality.HotChoc+"");
        HotChocUpdate.setText("0");

        my.Step1.Speciality.MintChoc+=Integer.parseInt(MintHotChocUpdate.getText());
        jTextMintChoc.setText(my.Step1.Speciality.MintChoc+"");
        MintHotChocUpdate.setText("0");

        my.Step1.Speciality.ChickenSoup+=Integer.parseInt(ChikSoupUpdate.getText());
        jTextChikSoup.setText(my.Step1.Speciality.ChickenSoup+"");
        ChikSoupUpdate.setText("0");

        my.Step1.Speciality.VegSoup+=Integer.parseInt(VegSoupUpdate.getText());
        jTextVegSoup.setText(my.Step1.Speciality.VegSoup+"");
        VegSoupUpdate.setText("0");


    }//GEN-LAST:event_SpecialityUpdateStockActionPerformed

    private void CoinsUpdateStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoinsUpdateStockActionPerformed
        //Updates Coins stock\\
        my.Step1.Pay.TwoEuro+=Integer.parseInt(TwoEuroUpdate.getText());
        jTextTwoEuro.setText(my.Step1.Pay.TwoEuro+"");
        TwoEuroUpdate.setText("0");

        my.Step1.Pay.OneEuro+=Integer.parseInt(OneEuroUpdate.getText());
        jTextOneEuro.setText(my.Step1.Pay.OneEuro+"");
        OneEuroUpdate.setText("0");

        my.Step1.Pay.FiftyCent+=Integer.parseInt(FiftyCentUpdate.getText());
        jTextFiftyCent.setText(my.Step1.Pay.FiftyCent+"");
        FiftyCentUpdate.setText("0");

        my.Step1.Pay.TwentyCent+=Integer.parseInt(TwentyCentUpdate.getText());
        jTextTwentyCent.setText(my.Step1.Pay.TwentyCent+"");
        TwentyCentUpdate.setText("0");

        my.Step1.Pay.TenCent+=Integer.parseInt(TenCentUpdate.getText());
        jTextFieldTenCent.setText(my.Step1.Pay.TenCent+"");
        TenCentUpdate.setText("0");

    }//GEN-LAST:event_CoinsUpdateStockActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BrewedUpdateStock;
    private javax.swing.JTextField CafeAmerUpdate;
    private javax.swing.JTextField CafeMochaUpdate;
    private javax.swing.JTextField CappUpdate;
    private javax.swing.JTextField ChikSoupUpdate;
    private javax.swing.JButton CoinsUpdateStock;
    private javax.swing.JTextField FiftyCentUpdate;
    private javax.swing.JTextField FlavCoffeeUpdate;
    private javax.swing.JTextField GoldBlendUpdate;
    private javax.swing.JTextField GreenTeaUpdate;
    private javax.swing.JTextField HotChocUpdate;
    private javax.swing.JTextField HouseBlendDecafUpdate;
    private javax.swing.JTextField HouseBlendRegUpdate;
    private javax.swing.JTextField MintHotChocUpdate;
    private javax.swing.JTextField OneEuroUpdate;
    private javax.swing.JTextField PepGreenTeaUpdate;
    private javax.swing.JButton SpecialityUpdateStock;
    private javax.swing.JButton TeasUpdateStock;
    private javax.swing.JTextField TenCentUpdate;
    private javax.swing.JTextField TwentyCentUpdate;
    private javax.swing.JTextField TwoEuroUpdate;
    private javax.swing.JTextField VegSoupUpdate;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelHouseBlend;
    private javax.swing.JLabel jLabelHouseBlendDecaf;
    private javax.swing.JTextField jTextChikSoup;
    private javax.swing.JTextField jTextFieldAmericano;
    private javax.swing.JTextField jTextFieldCapp;
    private javax.swing.JTextField jTextFieldFlavCoffee;
    private javax.swing.JTextField jTextFieldHouseDecaf;
    private javax.swing.JTextField jTextFieldHouseReg;
    private javax.swing.JTextField jTextFieldMocha;
    private javax.swing.JTextField jTextFieldTenCent;
    private javax.swing.JTextField jTextFiftyCent;
    private javax.swing.JTextField jTextGoldBlend;
    private javax.swing.JTextField jTextGreenTea;
    private javax.swing.JTextField jTextHotChocolate;
    private javax.swing.JTextField jTextMintChoc;
    private javax.swing.JTextField jTextOneEuro;
    private javax.swing.JTextField jTextPepGreenTea;
    private javax.swing.JTextField jTextTwentyCent;
    private javax.swing.JTextField jTextTwoEuro;
    private javax.swing.JTextField jTextVegSoup;
    // End of variables declaration//GEN-END:variables

}
