/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Teas.java
 *
 * Created on Oct 14, 2012, 3:49:18 PM
 */

package my.Step1;
//Imports JOption Pane\\
import javax.swing.JOptionPane;

/**
 *
 * @author conor
 */
public class Teas extends javax.swing.JFrame {
    //Creates flag for opening and clossing frame\\
    public static boolean teaFlag=false;
    
    //Creates flag for prices of each item picked\\
    public static boolean priceGoldBlend=false ;
    public static boolean priceGreenTea=false ;
    public static boolean pricePepGreenTea=false ;

    //Creates flag of current stock\\
    public static int GoldBlend = 4 ;
    public static int GreenTea = 4 ;
    public static int PepGreenTea = 4 ;

    /** Creates new form Teas */
    public Teas() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonPepGreenTea = new javax.swing.JButton();
        jButtonGoldBlend = new javax.swing.JButton();
        jButtonGreenTea = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(587, 455));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setText("Hot Gourmet Teas");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(320, 50, 150, 17);

        jButtonPepGreenTea.setFont(new java.awt.Font("Trajan Pro", 0, 18));
        jButtonPepGreenTea.setText("Peppermint Green Tea");
        jButtonPepGreenTea.setInheritsPopupMenu(true);
        jButtonPepGreenTea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPepGreenTeaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPepGreenTea);
        jButtonPepGreenTea.setBounds(240, 190, 270, 27);

        jButtonGoldBlend.setFont(new java.awt.Font("Trajan Pro", 0, 18));
        jButtonGoldBlend.setText("Gold Blend");
        jButtonGoldBlend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGoldBlendActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGoldBlend);
        jButtonGoldBlend.setBounds(240, 90, 270, 27);

        jButtonGreenTea.setFont(new java.awt.Font("Trajan Pro", 0, 18));
        jButtonGreenTea.setText("Green Tea");
        jButtonGreenTea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGreenTeaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGreenTea);
        jButtonGreenTea.setBounds(240, 140, 270, 27);

        jButtonBack.setFont(new java.awt.Font("Trajan Pro", 1, 18));
        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBack);
        jButtonBack.setBounds(440, 390, 100, 27);

        jLabel2.setFont(new java.awt.Font("Trajan Pro", 1, 14));
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("€3.00");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(510, 190, 50, 30);

        jLabel3.setFont(new java.awt.Font("Trajan Pro", 1, 14));
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("€2.00");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(510, 90, 50, 30);

        jLabel4.setFont(new java.awt.Font("Trajan Pro", 1, 14));
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("€2.00");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(510, 140, 50, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Step2.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 560, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // Takes you back to start frame//
        Step1 Step=new Step1 ();
        Step.setVisible (true) ;
        setVisible (false) ;
        dispose ();
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonPepGreenTeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPepGreenTeaActionPerformed
        //Checks if there is enough stock if not sets to red and shows JOptionPane//
        if(PepGreenTea<=0){
        jButtonPepGreenTea.setForeground(new java.awt.Color(255, 0, 0));
                JOptionPane.showMessageDialog(null, "Out Of Stock");
        }
        // If there is enough Stock this takes you to the next page\\
            else{
                Size Siz=new Size ();
                Siz.setVisible (true) ;
                setVisible (false) ;
                dispose ();
            }
        //Declare which button has been pressed using flags\\
        priceGoldBlend=false ;
        priceGreenTea=false ;
        pricePepGreenTea=true ;

        
    }//GEN-LAST:event_jButtonPepGreenTeaActionPerformed

    private void jButtonGoldBlendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGoldBlendActionPerformed
        //Checks if there is enough stock if not sets to red and shows JOptionPane//
        if(GoldBlend<=0){ 
        jButtonGoldBlend.setForeground(new java.awt.Color(255, 0, 0));
                JOptionPane.showMessageDialog(null, "Out Of Stock");
        }
        // If there is enough Stock this takes you to the next page\\
            else{
                Size Siz=new Size ();
                Siz.setVisible (true) ;
                setVisible (false) ;
                dispose ();
            }
        //Declare which button has been pressed using flags\\
        priceGoldBlend=true ;
        priceGreenTea=false ;
        pricePepGreenTea=false ;

      
    }//GEN-LAST:event_jButtonGoldBlendActionPerformed

    private void jButtonGreenTeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGreenTeaActionPerformed
        //Checks if there is enough stock if not sets to red and shows JOptionPane//
        if(GreenTea<=0){ 
        jButtonGreenTea.setForeground(new java.awt.Color(255, 0, 0));
                JOptionPane.showMessageDialog(null, "Out Of Stock");
        }
        // If there is enough Stock this takes you to the next page\\
            else{
                Size Siz=new Size ();
                Siz.setVisible (true) ;
                setVisible (false) ;
                dispose ();
            }
        //Declare which button has been pressed using flags\\
        priceGoldBlend=false ;
        priceGreenTea=true ;
        pricePepGreenTea=false ;

        
    }//GEN-LAST:event_jButtonGreenTeaActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        //Declare which page has been opened using flags\\
        teaFlag=true;
        my.Step1.Speciality.specialFlag=false;
        my.Step1.Brewed.brewedFlag=false;
    }//GEN-LAST:event_formWindowActivated

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonGoldBlend;
    private javax.swing.JButton jButtonGreenTea;
    private javax.swing.JButton jButtonPepGreenTea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables

}
